stages:
  - build
  - deploy


build:html:
  image: kominoshja/c68-sphinx:latest
  stage: build
  script:
  - git clone https://github.com/Blendify/sphinx-bootstrap-directives.git
  - rm -Rf sphinx-bootstrap-directives/docs/source
  - git clone https://git.collective68.tech/works/read-the-docs/collective68/offline-version.git _themes/sphinx_rtd_theme
  - make html
  - cd _build/html
  - rm -rf objects.inv .doctrees _raw_sources sphinx-bootstrap-directives .buildinfo
  - zip -r documentation.zip .
  - mv documentation.zip ../..
  artifacts:
    paths:
    - documentation.zip

pages:
  image: kominoshja/c68-sphinx:latest
  stage: deploy
  script:
  - git clone https://github.com/Blendify/sphinx-bootstrap-directives.git
  - rm -Rf sphinx-bootstrap-directives/docs/source
  - git clone https://git.collective68.tech/works/read-the-docs/collective68/online-version.git _themes/sphinx_rtd_theme
  - make html
  - sphinx-build -b pdf . _build/html/
  - mv _build/html public
  - mv documentation.zip public
  - rm -rf public/objects.inv public/.doctrees public/_raw_sources public/sphinx-bootstrap-directives public/.buildinfo
  dependencies:
    - build:html
  artifacts:
    paths:
    - public
  only:
  - master
